apiVersion: v1
metadata:
  name: gitlab-runner
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: gitrunner
    name: gitrunner
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: zhrum/gitrunner
      from:
        kind: DockerImage
        name: zhrum/gitrunner
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: gitrunner
    name: gitrunner
  spec:
    replicas: 1
    selector:
      app: gitrunner
      deploymentconfig: gitrunner
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: gitrunner
          deploymentconfig: gitrunner
      spec:
        containers:
        - env:
          - name: CI_RUNNER_TOKEN
            value: ${TOKEN}
          - name: CI_SERVER_URL
            value: ${URL}
          - name: RUNNER_NAME
            value: ${NAME}
          image: ' '
          imagePullPolicy: Always
          name: gitrunner
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/gitlab-runner
            name: gitrunner-volume-1
          - mountPath: /home/gitlab-runner
            name: gitrunner-volume-2
        volumes:
        - emptyDir: {}
          name: gitrunner-volume-1
        - emptyDir: {}
          name: gitrunner-volume-2
        serviceAccountName: ${USER}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitrunner
        from:
          kind: ImageStreamTag
          name: gitrunner:latest
      type: ImageChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: gruser
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: edit
  groupNames: null
  subjects:
    - kind: ServiceAccount
      name: gruser
  roleRef:
    name: edit
kind: Template
parameters:
- name: TOKEN
  value: 
- name: URL
  value: 
- name: NAME
  value: test
- name: USER
  value: gruser
